baseURL: https://merry-duckanoo-a1c829.netlify.app/
languageCode: en-us
title: Boz's Blog
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here you'll find a lot of cool information about a lot of stuff.
  SocialIcons:
    - name: facebook
      url: "https://facewbook.com/"
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/"

  comments: true

  cover:
    linkfullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10 
    - identifier: about
      name: About
      url: /about/
      weight: 10 